version: '3.8'

services:
  datingapp:
    image: smilkov/datingapp:latest
    ports:
      - "5000:8080"
    depends_on:
      - sql
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql;Database=datingdb;User Id=sa;Password=Password@1;TrustServerCertificate=True;"
      TokenKey: "Super secret unguesable secret key Super secret unguesable secret key Super secret unguesable secret key Super secret unguesable secret key"
      CloudinarySettings__CloudName: "duyhyhl0i"
      CloudinarySettings__ApiKey: "713634394119584"
      CloudinarySettings__ApiSecret: "lMz8nlNMejTfMuLfr0SOcmGlkc0"

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@1"
    platform: "linux/amd64"
    ports:
      - "1433:1433"
