apiVersion: apps/v1
kind: Deployment
metadata:
  name: datingapp
  namespace: datingapp
  labels:
    app: datingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datingapp
  template:
    metadata:
      labels:
        app: datingapp
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-sql
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mssql 1433; do echo "waiting for mssql"; sleep 3; done']
      containers:
        - name: api
          image: smilkov/datingapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: datingapp
  namespace: datingapp
  labels:
    app: datingapp
spec:
  selector:
    app: datingapp
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
